version: "3.9"

services:
  db:
    image: postgres:16
    container_name: timelog-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-timelog}
      POSTGRES_USER: ${POSTGRES_USER:-timelog}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-timelog}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    name: timelog-pgdata

