# Generated by Django 5.2.5 on 2025-08-10 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Arbeitstag für diesen Zeiteintrag",
                        verbose_name="Datum",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Beginn der Arbeitszeit", verbose_name="Startzeit"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="Ende der Arbeitszeit", verbose_name="Endzeit"
                    ),
                ),
                (
                    "lunch_break_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Dauer der Mittagspause in Minuten",
                        verbose_name="Mittagspause (Minuten)",
                    ),
                ),
                (
                    "pollution_level",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Niedrig"), (2, "Mittel"), (3, "Hoch")],
                        default=1,
                        help_text="Grad der Umweltverschmutzung am Arbeitsplatz (1=niedrig, 2=mittel, 3=hoch)",
                        verbose_name="Verschmutzungsgrad",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optionale Notizen zum Arbeitstag",
                        null=True,
                        verbose_name="Notizen",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Benutzer, der diesen Eintrag erstellt hat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_time_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="Benutzer, der diesen Eintrag zuletzt aktualisiert hat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_time_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aktualisiert von",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Der Mitarbeiter für diesen Zeiteintrag",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zeiteintrag",
                "verbose_name_plural": "Zeiteinträge",
                "ordering": ["-date", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="unique_user_date"
                    )
                ],
            },
        ),
    ]
