# Generated by Django 5.2.5 on 2025-08-11 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_timeentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeNonWorkingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        choices=[
                            ("specific", "Spezifisches Datum"),
                            ("weekly", "Wöchentlich wiederkehrend"),
                            ("monthly", "Monatlich wiederkehrend"),
                        ],
                        default="specific",
                        help_text="Art des arbeitsfreien Tages",
                        max_length=20,
                        verbose_name="Muster",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Spezifisches Datum (nur bei 'Spezifisches Datum')",
                        null=True,
                        verbose_name="Datum",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Montag"),
                            (1, "Dienstag"),
                            (2, "Mittwoch"),
                            (3, "Donnerstag"),
                            (4, "Freitag"),
                            (5, "Samstag"),
                            (6, "Sonntag"),
                        ],
                        help_text="Wochentag (nur bei 'Wöchentlich wiederkehrend')",
                        null=True,
                        verbose_name="Wochentag",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Tag des Monats (nur bei 'Monatlich wiederkehrend')",
                        null=True,
                        verbose_name="Tag des Monats",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Startdatum der Gültigkeit (optional)",
                        null=True,
                        verbose_name="Gültig ab",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Enddatum der Gültigkeit (optional)",
                        null=True,
                        verbose_name="Gültig bis",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Grund für den arbeitsfreien Tag (z.B. 'Teilzeit', 'Urlaub')",
                        max_length=200,
                        null=True,
                        verbose_name="Grund",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Mitarbeiter für den dieser arbeitsfreie Tag gilt",
                        limit_choices_to={"role": "employee"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arbeitsfreier Tag (Mitarbeiter)",
                "verbose_name_plural": "Arbeitsfreie Tage (Mitarbeiter)",
                "ordering": ["employee", "date", "weekday"],
            },
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name des Feiertags (z.B. 'Neujahr', 'Weihnachten')",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Datum des Feiertags", verbose_name="Datum"
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Wiederholt sich dieser Feiertag jährlich am gleichen Datum?",
                        verbose_name="Jährlich wiederkehrend",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optionale Beschreibung des Feiertags",
                        null=True,
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
            ],
            options={
                "verbose_name": "Feiertag",
                "verbose_name_plural": "Feiertage",
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "date"), name="unique_holiday_name_date"
                    )
                ],
            },
        ),
    ]
