# Generated by Django 5.2.5 on 2025-08-11 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_employeenonworkingday_publicholiday"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        help_text="Fahrzeugkennzeichen (eindeutig)",
                        max_length=20,
                        unique=True,
                        verbose_name="Kennzeichen",
                    ),
                ),
                (
                    "make",
                    models.CharField(
                        help_text="Fahrzeughersteller (z.B. 'Volkswagen', 'BMW')",
                        max_length=50,
                        verbose_name="Marke",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Fahrzeugmodell (z.B. 'Golf', '3er')",
                        max_length=50,
                        verbose_name="Modell",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Baujahr des Fahrzeugs", verbose_name="Baujahr"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Fahrzeugfarbe (optional)",
                        max_length=30,
                        verbose_name="Farbe",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Benzin"),
                            ("diesel", "Diesel"),
                            ("electric", "Elektro"),
                            ("hybrid", "Hybrid"),
                            ("other", "Sonstiges"),
                        ],
                        default="petrol",
                        help_text="Art des Kraftstoffs",
                        max_length=20,
                        verbose_name="Kraftstoffart",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Ist das Fahrzeug derzeit verfügbar?",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Zusätzliche Informationen zum Fahrzeug",
                        verbose_name="Notizen",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
            ],
            options={
                "verbose_name": "Fahrzeug",
                "verbose_name_plural": "Fahrzeuge",
                "ordering": ["license_plate"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="default_vehicle",
            field=models.ForeignKey(
                blank=True,
                help_text="Standard-Fahrzeug für diesen Mitarbeiter",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.vehicle",
                verbose_name="Standard-Fahrzeug",
            ),
        ),
        migrations.CreateModel(
            name="VehicleUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_kilometers",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Kilometerstand zu Beginn der Arbeitszeit",
                        null=True,
                        verbose_name="Anfangs-km",
                    ),
                ),
                (
                    "end_kilometers",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Kilometerstand am Ende der Arbeitszeit",
                        null=True,
                        verbose_name="End-km",
                    ),
                ),
                (
                    "no_vehicle_used",
                    models.BooleanField(
                        default=False,
                        help_text="Aktivieren wenn kein Fahrzeug verwendet wurde",
                        verbose_name="Kein Fahrzeug verwendet",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Zusätzliche Informationen zur Fahrzeugnutzung",
                        verbose_name="Notizen",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "time_entry",
                    models.OneToOneField(
                        help_text="Verknüpfter Zeiteintrag",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.timeentry",
                        verbose_name="Zeiteintrag",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Verwendetes Fahrzeug (leer wenn kein Fahrzeug verwendet)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.vehicle",
                        verbose_name="Fahrzeug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fahrzeugnutzung",
                "verbose_name_plural": "Fahrzeugnutzungen",
                "ordering": ["-time_entry__date"],
            },
        ),
    ]
