name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: CI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements*.txt

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install -r requirements.txt; fi

      - name: Requirements sanity check
        run: pip check

      - name: Security audit (advisory only)
        run: pip-audit || true

      - name: Code formatting check (Black)
        run: black --check .

      - name: Import sorting check (isort)
        run: isort --check-only .

      - name: Linting (flake8)
        run: flake8 .

      - name: Django system check
        run: python manage.py check

      - name: Check for missing migrations
        run: python manage.py makemigrations --check --dry-run

      - name: Run migrations
        run: python manage.py migrate --noinput

      - name: Run tests with coverage
        run: pytest --cov=. --cov-report=xml --cov-report=term-missing --cov-fail-under=90

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml